[package]
name = "slipstream"
version = "0.2.1"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
edition = "2018"
description = "SIMD library usable by the masses"
repository = "http://github.com/vorner/splitstream"
readme = "README.md"
keywords = ["simd", "performance"]
categories = ["hardware-support"]
license = "Apache-2.0 OR MIT"
autobenches = false

[badges]
travis-ci = { repository = "vorner/arc-swap" }
maintenance = { status = "actively-developed" }

[workspace]
members = ["benchmarks"]

[dependencies]
num-traits = "0.2"
# Required by examples
iterator_ilp = { version = "1.0", optional = true }

[dev-dependencies]
criterion = "~0.3"
iterator_ilp = "1.0"
multiversion = "~0.6"
proptest = "~0.10"
rand = "~0.8"

[profile.release]
debug = 2

[profile.test]
# Some tests are slow to run. Even slower than it takes to compile them properly.
opt-level = 1

[[bench]]
name = "track"
harness = false
